// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/discord.proto

package discord

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildsRequest) Reset() {
	*x = GetGuildsRequest{}
	mi := &file_proto_discord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildsRequest) ProtoMessage() {}

func (x *GetGuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildsRequest.ProtoReflect.Descriptor instead.
func (*GetGuildsRequest) Descriptor() ([]byte, []int) {
	return file_proto_discord_proto_rawDescGZIP(), []int{0}
}

type GetGuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guilds        []*GuildInfo           `protobuf:"bytes,1,rep,name=guilds,proto3" json:"guilds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGuildsResponse) Reset() {
	*x = GetGuildsResponse{}
	mi := &file_proto_discord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGuildsResponse) ProtoMessage() {}

func (x *GetGuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGuildsResponse.ProtoReflect.Descriptor instead.
func (*GetGuildsResponse) Descriptor() ([]byte, []int) {
	return file_proto_discord_proto_rawDescGZIP(), []int{1}
}

func (x *GetGuildsResponse) GetGuilds() []*GuildInfo {
	if x != nil {
		return x.Guilds
	}
	return nil
}

type GuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildInfo) Reset() {
	*x = GuildInfo{}
	mi := &file_proto_discord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildInfo) ProtoMessage() {}

func (x *GuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildInfo.ProtoReflect.Descriptor instead.
func (*GuildInfo) Descriptor() ([]byte, []int) {
	return file_proto_discord_proto_rawDescGZIP(), []int{2}
}

func (x *GuildInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GuildInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

var File_proto_discord_proto protoreflect.FileDescriptor

const file_proto_discord_proto_rawDesc = "" +
	"\n" +
	"\x13proto/discord.proto\x12\adiscord\"\x12\n" +
	"\x10GetGuildsRequest\"?\n" +
	"\x11GetGuildsResponse\x12*\n" +
	"\x06guilds\x18\x01 \x03(\v2\x12.discord.GuildInfoR\x06guilds\"C\n" +
	"\tGuildInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon2K\n" +
	"\x05Guild\x12B\n" +
	"\tGetGuilds\x12\x19.discord.GetGuildsRequest\x1a\x1a.discord.GetGuildsResponseB\x11Z\x0f./proto;discordb\x06proto3"

var (
	file_proto_discord_proto_rawDescOnce sync.Once
	file_proto_discord_proto_rawDescData []byte
)

func file_proto_discord_proto_rawDescGZIP() []byte {
	file_proto_discord_proto_rawDescOnce.Do(func() {
		file_proto_discord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_discord_proto_rawDesc), len(file_proto_discord_proto_rawDesc)))
	})
	return file_proto_discord_proto_rawDescData
}

var file_proto_discord_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_discord_proto_goTypes = []any{
	(*GetGuildsRequest)(nil),  // 0: discord.GetGuildsRequest
	(*GetGuildsResponse)(nil), // 1: discord.GetGuildsResponse
	(*GuildInfo)(nil),         // 2: discord.GuildInfo
}
var file_proto_discord_proto_depIdxs = []int32{
	2, // 0: discord.GetGuildsResponse.guilds:type_name -> discord.GuildInfo
	0, // 1: discord.Guild.GetGuilds:input_type -> discord.GetGuildsRequest
	1, // 2: discord.Guild.GetGuilds:output_type -> discord.GetGuildsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_discord_proto_init() }
func file_proto_discord_proto_init() {
	if File_proto_discord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_discord_proto_rawDesc), len(file_proto_discord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_discord_proto_goTypes,
		DependencyIndexes: file_proto_discord_proto_depIdxs,
		MessageInfos:      file_proto_discord_proto_msgTypes,
	}.Build()
	File_proto_discord_proto = out.File
	file_proto_discord_proto_goTypes = nil
	file_proto_discord_proto_depIdxs = nil
}
