// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/discord.proto

package discord

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Guild_GetGuilds_FullMethodName = "/discord.Guild/GetGuilds"
)

// GuildClient is the client API for Guild service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuildClient interface {
	GetGuilds(ctx context.Context, in *GetGuildsRequest, opts ...grpc.CallOption) (*GetGuildsResponse, error)
}

type guildClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildClient(cc grpc.ClientConnInterface) GuildClient {
	return &guildClient{cc}
}

func (c *guildClient) GetGuilds(ctx context.Context, in *GetGuildsRequest, opts ...grpc.CallOption) (*GetGuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGuildsResponse)
	err := c.cc.Invoke(ctx, Guild_GetGuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildServer is the server API for Guild service.
// All implementations must embed UnimplementedGuildServer
// for forward compatibility.
type GuildServer interface {
	GetGuilds(context.Context, *GetGuildsRequest) (*GetGuildsResponse, error)
	mustEmbedUnimplementedGuildServer()
}

// UnimplementedGuildServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildServer struct{}

func (UnimplementedGuildServer) GetGuilds(context.Context, *GetGuildsRequest) (*GetGuildsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuilds not implemented")
}
func (UnimplementedGuildServer) mustEmbedUnimplementedGuildServer() {}
func (UnimplementedGuildServer) testEmbeddedByValue()               {}

// UnsafeGuildServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildServer will
// result in compilation errors.
type UnsafeGuildServer interface {
	mustEmbedUnimplementedGuildServer()
}

func RegisterGuildServer(s grpc.ServiceRegistrar, srv GuildServer) {
	// If the following call pancis, it indicates UnimplementedGuildServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Guild_ServiceDesc, srv)
}

func _Guild_GetGuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildServer).GetGuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guild_GetGuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildServer).GetGuilds(ctx, req.(*GetGuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Guild_ServiceDesc is the grpc.ServiceDesc for Guild service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Guild_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discord.Guild",
	HandlerType: (*GuildServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGuilds",
			Handler:    _Guild_GetGuilds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discord.proto",
}
